name: CI

on:
  - push

jobs:
  oxfmt:
    runs-on: ubuntu-latest
    name: Check formatting
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: "npm"
      - run: npm ci
      - run: npx oxfmt --check

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v7
        with:
          name: redirect-origin
          path: dist/
          if-no-files-found: error
