name: CI

on:
  - push

jobs:
  oxfmt:
    runs-on: ubuntu-latest
    name: Check formatting
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9
      - uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: "pnpm"
      - run: pnpm ci
      - run: pnpx oxfmt --check

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9
      - uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: "pnpm"
      - run: pnpm ci
      - run: pnpm run build
      - uses: actions/upload-artifact@v7
        with:
          name: redirect-origin
          path: dist/
          if-no-files-found: error
